// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkQgbQGz89EXcP-27numZQNQRZ-hdEjwQ',
    appId: '1:216006217728:web:50e95d6a6c75b7b19ec8e5',
    messagingSenderId: '216006217728',
    projectId: 'transport-issue-tracking-app',
    authDomain: 'transport-issue-tracking-app.firebaseapp.com',
    databaseURL: 'https://transport-issue-tracking-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transport-issue-tracking-app.firebasestorage.app',
    measurementId: 'G-6W91Q8Y21Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2cEi_WIyk5Cu7RyjEAZABcGSD3okigPY',
    appId: '1:216006217728:android:2f617aea48209e489ec8e5',
    messagingSenderId: '216006217728',
    projectId: 'transport-issue-tracking-app',
    databaseURL: 'https://transport-issue-tracking-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transport-issue-tracking-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxrzoWuAPVJVizdGHxReZ2XWbghptL_Os',
    appId: '1:216006217728:ios:5a9b8a7cc18b90309ec8e5',
    messagingSenderId: '216006217728',
    projectId: 'transport-issue-tracking-app',
    databaseURL: 'https://transport-issue-tracking-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transport-issue-tracking-app.firebasestorage.app',
    iosBundleId: 'com.example.transportTrackingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxrzoWuAPVJVizdGHxReZ2XWbghptL_Os',
    appId: '1:216006217728:ios:5a9b8a7cc18b90309ec8e5',
    messagingSenderId: '216006217728',
    projectId: 'transport-issue-tracking-app',
    databaseURL: 'https://transport-issue-tracking-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transport-issue-tracking-app.firebasestorage.app',
    iosBundleId: 'com.example.transportTrackingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkQgbQGz89EXcP-27numZQNQRZ-hdEjwQ',
    appId: '1:216006217728:web:2fb3d12c0a7e9aa79ec8e5',
    messagingSenderId: '216006217728',
    projectId: 'transport-issue-tracking-app',
    authDomain: 'transport-issue-tracking-app.firebaseapp.com',
    databaseURL: 'https://transport-issue-tracking-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'transport-issue-tracking-app.firebasestorage.app',
    measurementId: 'G-9ZSQGCXPLW',
  );
}
